### ISSUE TITLE
Questions about SPC chart 1 - weekly time in mod/sev pain

### ISSUE THREAD

**Issue by SJaffa** [inform-us/metrics-rules#4]
### Chart 1
https://github.com/inform-us/metrics-rules/blob/fdea8cb99d47fc8c61bacd744fa7fe5e04800541/rules/pain.md?plain=1#L109-L118

- Eligible hours is all hours with a valid pain score- does this include backfilled?
- Calendar day is 00:00 - 23:59 ?
- Get a daily number for each patient of (Number of hours in amber or red) divided by (number of hours eligible)
- Pool these together for all patients for the week - "pool" means add or average?

**Comment by VoegeleP** [comment]
Eligible hours is all hours with a valid pain score- does this include backfilled? Yes as these scores are still valid. 
Calendar day is 00:00 - 23:59 ? Yes
Get a daily number for each patient of (Number of hours in amber or red) divided by (number of hours eligible). Not sure what this means. Is this a question? 
Pool these together for all patients for the week - "pool" means add or average? I think we mean add them together and then average them... Is that what you mean?

**Comment by SiriHope** [comment]
Q2- yes this is what we do, but I wasn't sure if you were asking if that is what we do or...?
Q3. yes it's the mean of all the calendar day calculations over 7 days.
